In [1]:
!pip install SomaData

Collecting SomaData
  Downloading somadata-1.2.6-py3-none-any.whl.metadata (151 kB)
Requirement already satisfied: numpy>=1.19 in /opt/conda/lib/python3.12/site-packages (from SomaData) (2.5.1)
Collecting openpyxl>=3.0 (from SomaData)
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pandas>=1.1.2 in /opt/conda/lib/python3.12/site-packages (from SomaData) (2.3.2)
Collecting et-xmlfile (from openpyxl>=3.0->SomaData)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.1.2->SomaData) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.1.2->SomaData) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.1.2->SomaData) (2026.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.2->SomaData) (1.16.0)
Downloading somadata-1.2.6-py3-none-any.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 119.0 MB/s  0:00:00
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl, SomaData
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [SomaData]1/3 [openpyxl]
Successfully installed SomaData-1.2.6 et-xmlfile-2.0.0 openpyxl-3.1.5

In [2]:
import pandas as pd
import somadata as sd

In [3]:
adat = sd.read_adat(
    "/mnt/data/raw/SS-217041.raw.adat"
)

In [4]:
# Extract Feature Data
features = adat.columns.to_frame(index=False).rename({"SeqId": "ProbeId"}, axis = 1)
features.to_csv(
    "/mnt/data/processed/features.csv",
    index=False
)
features

,ProbeId,SeqIdVersion,SomaId,TargetFullName,Target,UniProt,EntrezGeneID,EntrezGeneSymbol,Organism,Units,Type,Dilution
0,10000-28,3,SL019233,Beta-crystallin B2,CRBB2,P43320,1415,CRYBB2,Human,RFU,Protein,20
1,10001-7,3,SL002564,RAF proto-oncogene serine/threonine-protein ki...,c-Raf,P04049,5894,RAF1,Human,RFU,Protein,20
2,10003-15,3,SL019245,Zinc finger protein 41,ZNF41,P51814,7592,ZNF41,Human,RFU,Protein,0.5
3,10006-25,3,SL019228,ETS domain-containing protein Elk-1,ELK1,P19419,2002,ELK1,Human,RFU,Protein,20
4,10008-43,3,SL019234,Guanylyl cyclase-activating protein 1,GUC1A,P43080,2978,GUCA1A,Human,RFU,Protein,20
...,...,...,...,...,...,...,...,...,...,...,...,...
7591,9993-11,3,SL019212,Zinc finger protein 264,ZN264,O43296,9422,ZNF264,Human,RFU,Protein,20
7592,9994-217,3,SL019217,Potassium-transporting ATPase subunit beta,ATP4B,P51164,496,ATP4B,Human,RFU,Protein,20
7593,9995-6,3,SL013164,Deoxyuridine 5'-triphosphate nucleotidohydrola...,DUT,P33316,1854,DUT,Human,RFU,Protein,20
7594,9997-12,3,SL026026,UBX domain-containing protein 4:Cytoplasmic do...,UBXN4:CD 1,Q92575,23190,UBXN4,Human,RFU,Protein,20
7595,9999-1,3,SL019231,Interferon regulatory factor 6,IRF6,O14896,3664,IRF6,Human,RFU,Protein,20

In [5]:
# Extract Sample Data
samples = adat.index.to_frame().reset_index(drop = True)
samples.to_csv(
    "/mnt/data/processed/samples.csv",
    index=False
)
samples

,PlateId,PlateRunDate,ScannerID,PlatePosition,SlideId,Subarray,SampleId,SampleType,PercentDilution,SampleMatrix,...,SampleDescription,AssayNotes,TimePoint,ExtIdentifier,SsfExtId,SampleGroup,SiteId,SubjectID,CLI,RMA
0,P0031168,2021-12-03,SG12344217,A1,258633829464,1,5302-15,Sample,20,EDTA plasma,...,,,,EXID40000006690911,EID656975,,,,CLI8007F183,SS-217041
1,P0031168,2021-12-03,SG12344217,A10,258633829473,1,4875-1,Sample,20,EDTA plasma,...,,,,EXID40000006690909,EID657047,,,,CLI8007F183,SS-217041
2,P0031168,2021-12-03,SG12344217,A11,258633829518,1,824-29,Sample,20,EDTA plasma,...,,,,EXID40000006690925,EID657055,,,,CLI8007F183,SS-217041
3,P0031168,2021-12-03,SG12344217,A12,258633829519,1,4922-2,Sample,20,EDTA plasma,...,,,,EXID40000006690906,EID657063,,,,CLI8007F183,SS-217041
4,P0031168,2021-12-03,SG12344217,A2,258633829465,1,4913-2,Sample,20,EDTA plasma,...,,,,EXID40000006690763,EID656983,,,,CLI8007F183,SS-217041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2045,P0031201,2021-12-07,SG12064173,H5,258633834733,8,980-20,Sample,20,EDTA plasma,...,,,,EXID40000006724042,EID661496,,,,CLI8007F183,SS-217041
2046,P0031201,2021-12-07,SG12064173,H6,258633834734,8,4908-7,Sample,20,EDTA plasma,...,,,,EXID40000006724274,EID661504,,,,CLI8007F183,SS-217041
2047,P0031201,2021-12-07,SG12064173,H7,258633834735,8,6013-12,Sample,20,EDTA plasma,...,,,,EXID40000006724418,EID661512,,,,CLI8007F183,SS-217041
2048,P0031201,2021-12-07,SG12064173,H8,258633834736,8,5847-11,Sample,20,EDTA plasma,...,,,,EXID40000006724039,EID661520,,,,CLI8007F183,SS-217041
2049,P0031201,2021-12-07,SG12064173,H9,258633834737,8,110-18,Sample,20,EDTA plasma,...,,,,EXID40000006724300,EID661528,,,,CLI8007F183,SS-217041

In [6]:
# Extract Measurement Data
measurements = adat.reset_index(drop = True)
measurements.columns = features["ProbeId"]
measurements = pd.concat(
    [
        samples.loc[:, ["PlateId", "PlatePosition"]],
        measurements
    ],
    axis=1
)
measurements = measurements.melt(
    id_vars=["PlateId", "PlatePosition"],
    var_name="ProbeId"
)
measurements.to_csv(
    "/mnt/data/processed/measurements.raw.csv",
    index=False
)
measurements

           PlateId PlatePosition   ProbeId   value
0         P0031168            A1  10000-28   748.8
1         P0031168           A10  10000-28   577.5
2         P0031168           A11  10000-28   526.8
3         P0031168           A12  10000-28   508.4
4         P0031168            A2  10000-28   450.5
...            ...           ...       ...     ...
15571795  P0031201            H5    9999-1  2903.1
15571796  P0031201            H6    9999-1  1601.1
15571797  P0031201            H7    9999-1  7303.7
15571798  P0031201            H8    9999-1  6444.5
15571799  P0031201            H9    9999-1  1645.7

[15571800 rows x 4 columns]